### ISSUE TITLE
ArmCord doesn't work (white background)

### ISSUE THREAD

**Issue by milutinke** [smartfrigde/armcord#486]
**Describe the bug**
Arm Cord is broken past the setup screen all I get is a white background.

**To Reproduce**
Just launch it.

**Expected behavior**
Open up and work normally.

**Screenshots**
![image](https://github.com/ArmCord/ArmCord/assets/441903/8e2aadaf-bf8e-4674-a869-afe55acdc3c7)

**Desktop (please complete the following information):**
 - OS: `Linux arch 6.5.7-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC`
 - Method of installation: `AUR`
 - Version: `armcord-bin 3.2.4-2`
 - Window manager: `DWM`
 - Display porotocol: `X11`

**Additional context**
Everything was working until I updated my packages yesterday.

Errors from the log:
```
[40592:1015/110733.657930:ERROR:object_proxy.cc(590)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/portal/desktop: org.freedesktop.DBus.Error.InvalidArgs: No such interface „org.freedesktop.portal.FileChooser“
[40592:1015/110733.657966:ERROR:select_file_dialog_linux_portal.cc(274)] Failed to read portal version property

(node:40592) UnhandledPromiseRejectionWarning: TypeError: Object has been destroyed
    at IpcMainImpl.<anonymous> (/opt/armcord/resources/app.asar/ts-out/ipc.js:94:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
(Use `armcord --trace-warnings ...` to show where the warning was created)
(node:40592) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
```

I have `xdg-desktop-portal-kde` and `xdg-desktop-portal-gnome` installed, and the following xdg-desktop services running:
```
xdg-desktop-portal.service     loaded active running Portal service
xdg-document-portal.service    loaded active running flatpak document portal service
xdg-permission-store.service   loaded active running sandboxed app permission store
```

**Comment by rlad78** [comment]
I can also confirm this happens on both the current flathub and flathub-beta builds. This was my first time running the app on this machine (Fedora 38 Silverblue x86/64, Gnome 44.5 Wayland). Same errors as above appear when running the flatpak container. 

Two windows appear on launch: the "Welcome to ArmCord setup" window, and the normal Discord updater window. However, the Discord updater window has the text "Nothing to install" and closes after about 3 seconds. Once that window closes, the ArmCord setup window goes completely white and unresponsive. 

EDIT: falling back to an earlier commit on the flathub release fixed the issue:
```bash
sudo flatpak update --commit=82b918c4bff22c2822fbabd31abefb0b4660f3f62ec9ea96a16d5219a2ba94bd xyz.armcord.ArmCord
```

This was the commit submitted on 08/08/2023:
```
    Commit: 82b918c4bff22c2822fbabd31abefb0b4660f3f62ec9ea96a16d5219a2ba94bd
   Subject: Change icon in main branch (#34) (2dc9a9c7)
      Date: 2023-08-08 22:04:13 +0000
```

The following commits all had the same issue:
```
    Commit: 46e148e57578ad7129730e3dcf0ea77c60c1d1d39908ba5f3b7ad3d5edccf435
    Parent: f770c55473cc62000954261a1518c79c049ca1aee630a7a8c4474e1c3128ca34
   Subject: Drop kde own name (#43) (65d85aec)
      Date: 2023-09-28 17:20:50 +0000
   History: 

    Commit: f770c55473cc62000954261a1518c79c049ca1aee630a7a8c4474e1c3128ca34
   Subject: Update 2 modules (7ce17247)
      Date: 2023-08-26 21:21:40 +0000

    Commit: 319cd48d58e674aefa683da4d6470683fad980bfd1a08de47915234d979ae01c
   Subject: Add XCURSOR_PATH variable (#37) (db45fa67)
      Date: 2023-08-24 13:16:39 +0000
```

The latest working client is `ArmCord Version: 3.2.3`.
